# Numpy

## Installtaion

pip install numpy

In [1]:
import numpy as np

## Numpy vs Python List

In [2]:
l = range(1_000_000)
%time for i in range(1,10): r = [x*2 for x in l]

CPU times: total: 1.72 s
Wall time: 2.19 s


In [3]:
d = np.arange(1_000_000)
%time for i in range(1,10): r = d*2

CPU times: total: 46.9 ms
Wall time: 60.9 ms


## A Multidimensional Array Object

In [4]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
x = np.empty((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
l = [1,4,5,7]
x = np.array(l)
x

array([1, 4, 5, 7])

In [9]:
x = np.arange(1,100,5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [10]:
x.ndim

1

In [11]:
x.shape

(20,)

In [12]:
x = np.zeros((10,10))
x.shape

(10, 10)

In [13]:
y = x.reshape(2,2,5,5)

In [14]:
x.dtype

dtype('float64')

In [15]:
y.ndim

4

## Arithmetic with ndarray

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [18]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [20]:
arr ** 5

array([[   1,   32,  243],
       [1024, 3125, 7776]], dtype=int32)

In [21]:
arr2 = np.array([[0,4,1],[7,2,12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [22]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [23]:
a = np.random.randn((10))
b = np.random.randn((10))
a

array([-0.75557638,  0.83639376,  0.16070069,  1.02745103, -0.36652733,
       -0.12778847,  0.13428432,  0.86019937,  0.61231086,  0.76489377])

In [24]:
b

array([ 0.82275035, -0.93304838,  0.4590052 ,  0.67124739, -0.15058372,
        0.44183542, -0.55247907,  0.82958553,  1.95474529, -1.70063188])

In [25]:
a+b

array([ 0.06717397, -0.09665462,  0.6197059 ,  1.69869841, -0.51711105,
        0.31404695, -0.41819475,  1.6897849 ,  2.56705615, -0.93573811])

In [26]:
a-b

array([-1.57832674,  1.76944214, -0.29830451,  0.35620364, -0.21594361,
       -0.56962389,  0.68676339,  0.03061384, -1.34243443,  2.46552565])

In [27]:
2*b

array([ 1.6455007 , -1.86609675,  0.91801041,  1.34249477, -0.30116744,
        0.88367084, -1.10495814,  1.65917105,  3.90949058, -3.40126375])

In [28]:
1/a

array([-1.32349293,  1.19560911,  6.2227486 ,  0.9732824 , -2.72830951,
       -7.82543236,  7.44688574,  1.1625212 ,  1.63315738,  1.30737109])

In [29]:
a>0

array([False,  True,  True,  True, False, False,  True,  True,  True,
        True])

In [30]:
a>b

array([False,  True, False,  True, False, False,  True,  True, False,
        True])

In [31]:
a[a>0]

array([0.83639376, 0.16070069, 1.02745103, 0.13428432, 0.86019937,
       0.61231086, 0.76489377])

## Indexing & Slicing

In [32]:
x = np.array([1,7,9,8,5])
x

array([1, 7, 9, 8, 5])

In [33]:
x[2]

9

In [34]:
x[x>5]

array([7, 9, 8])

In [35]:
x[[2,1]]

array([9, 7])

In [36]:
x = np.random.randn(10,10)
x

array([[-2.1640335 ,  0.47555578, -0.24025077,  0.66637169, -0.43035663,
        -0.66802053,  0.72867056, -0.83707327, -0.64073359, -0.32642095],
       [ 1.37883455, -1.6470371 ,  0.6933915 , -0.38005567, -1.11614001,
        -0.6533667 ,  2.02325649,  0.34616971, -0.08470534,  1.89884021],
       [-0.86051812, -0.45887158,  0.42516928, -1.63657247, -1.02798048,
        -0.13682308,  0.93849793,  0.61013195,  0.34379456, -0.15203856],
       [ 0.860866  ,  0.77747898,  0.99786204, -1.43317537, -0.13546407,
        -0.02782074,  2.38278708, -0.31674924, -0.36433108,  0.52867243],
       [ 1.64027671,  0.90529251, -0.50416714, -0.72190426, -0.62127707,
         0.53699347, -1.07502084,  0.80375845, -0.33637728,  1.08473952],
       [ 0.00622295,  0.63101419, -1.7302012 , -1.26035118,  1.70285447,
        -0.68106895, -0.14172473,  2.04838227, -1.8114795 , -0.82054177],
       [ 3.18175948, -0.55924542, -2.50740753, -0.98929815,  0.8390934 ,
         0.96455079,  0.20987074, -1.16507719

In [37]:
x[0]

array([-2.1640335 ,  0.47555578, -0.24025077,  0.66637169, -0.43035663,
       -0.66802053,  0.72867056, -0.83707327, -0.64073359, -0.32642095])

In [38]:
x[0][4]

-0.43035662534501373

In [39]:
x[1:10:2,:]

array([[ 1.37883455, -1.6470371 ,  0.6933915 , -0.38005567, -1.11614001,
        -0.6533667 ,  2.02325649,  0.34616971, -0.08470534,  1.89884021],
       [ 0.860866  ,  0.77747898,  0.99786204, -1.43317537, -0.13546407,
        -0.02782074,  2.38278708, -0.31674924, -0.36433108,  0.52867243],
       [ 0.00622295,  0.63101419, -1.7302012 , -1.26035118,  1.70285447,
        -0.68106895, -0.14172473,  2.04838227, -1.8114795 , -0.82054177],
       [ 0.51287714,  0.42395263,  0.3161274 ,  0.74824952,  0.83055128,
         1.05378544,  0.96961116,  0.49007477, -0.12265702,  0.07389005],
       [ 0.43624046,  0.75189018, -0.74010802,  0.49229158,  0.27005816,
         0.43520626, -1.65533095, -0.70615293, -0.31433127,  0.9003808 ]])

In [40]:
x[::,0:4]

array([[-2.1640335 ,  0.47555578, -0.24025077,  0.66637169],
       [ 1.37883455, -1.6470371 ,  0.6933915 , -0.38005567],
       [-0.86051812, -0.45887158,  0.42516928, -1.63657247],
       [ 0.860866  ,  0.77747898,  0.99786204, -1.43317537],
       [ 1.64027671,  0.90529251, -0.50416714, -0.72190426],
       [ 0.00622295,  0.63101419, -1.7302012 , -1.26035118],
       [ 3.18175948, -0.55924542, -2.50740753, -0.98929815],
       [ 0.51287714,  0.42395263,  0.3161274 ,  0.74824952],
       [ 0.86392161,  0.44151511,  0.28900367,  0.09912573],
       [ 0.43624046,  0.75189018, -0.74010802,  0.49229158]])

In [44]:
x = np.ones((5,5),dtype="int8")
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [45]:
x[1:-1,1:-1]=0
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)