# Numpy

## Fast element-wise array functions

In [1]:
import numpy as np

In [2]:
x = np.array([10,9,8,6,11])
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [3]:
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [4]:
y = np.array([7,6,111,-1,0])
np.maximum(x,y)

array([ 10,   9, 111,   6,  11])

## Np.where

In [5]:
x = np.array([0,-1,1000,25,522])
x

array([   0,   -1, 1000,   25,  522])

In [6]:
np.where(x<=0,27,x)

array([  27,   27, 1000,   25,  522])

In [7]:
np.where(x<=0,"Not OK","OK")

array(['Not OK', 'Not OK', 'OK', 'OK', 'OK'], dtype='<U6')

## Mathematical & Statistical Methods

In [8]:
x = np.array([10,9,7,10,7])
x

array([10,  9,  7, 10,  7])

In [9]:
x.mean()

8.6

In [10]:
x.cumsum()

array([10, 19, 26, 36, 43])

In [11]:
x.cumprod()

array([   10,    90,   630,  6300, 44100])

In [12]:
y = x > 9
y

array([ True, False, False,  True, False])

In [13]:
y.sum()

2

In [14]:
y.any()

True

In [15]:
y.all()

False

In [16]:
x.sort()
x

array([ 7,  7,  9, 10, 10])

In [17]:
np.unique(x)

array([ 7,  9, 10])

## File Input Output

In [18]:
x = [1,4,5,7]
y = [8,7,9]

In [19]:
np.save("002_Numpy_file_1",x)

In [20]:
loadX = np.load("002_Numpy_file_1.npy")
loadX

array([1, 4, 5, 7])

In [21]:
np.savez("002_Numpy_file_2",x,y)

In [22]:
loadXY = np.load("002_Numpy_file_2.npz")
loadXY

## Linear Algebra Functions

In [23]:
x = np.random.randn(3,2)
y = np.random.randn(2,3)
x

array([[-1.1979868 , -0.9947829 ],
       [-1.06917585,  1.45432122],
       [ 0.18784476,  1.25674337]])

In [24]:
y

array([[-0.35298746,  1.7279275 ,  0.07935958],
       [ 1.18782508,  0.04032218, -1.25295147]])

In [25]:
x.dot(y)

array([[-0.75875376, -2.11014614,  1.15134297],
       [ 2.10488488, -1.78881696, -1.90704326],
       [ 1.42648444,  0.37525675, -1.55973116]])

In [26]:
x.transpose()

array([[-1.1979868 , -1.06917585,  0.18784476],
       [-0.9947829 ,  1.45432122,  1.25674337]])

In [27]:
x.trace()

0.25633442866201905

## Pseudo Random Number

In [28]:
np.random.seed(7)

In [29]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [30]:
np.random.uniform(size=(3,3))

array([[0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892]])