# Numpy

## NumPy Advanced Array Manipulations

In [1]:
import numpy as np

## Reshape

In [2]:
x = np.random.randn(4,5)
x

array([[-0.60854492,  0.46916285, -0.08461721, -0.03512837,  1.65916458],
       [-2.11961816, -0.64694338, -0.13860586, -0.43262796,  1.06048937],
       [ 0.3732861 , -0.26228621,  0.728369  ,  0.23094248, -1.6412629 ],
       [ 0.573722  ,  0.60064174, -0.72423121, -0.40414751,  1.63503788]])

In [3]:
x.reshape((2,2,5))

array([[[-0.60854492,  0.46916285, -0.08461721, -0.03512837,
          1.65916458],
        [-2.11961816, -0.64694338, -0.13860586, -0.43262796,
          1.06048937]],

       [[ 0.3732861 , -0.26228621,  0.728369  ,  0.23094248,
         -1.6412629 ],
        [ 0.573722  ,  0.60064174, -0.72423121, -0.40414751,
          1.63503788]]])

In [4]:
x.reshape((2,2,5),order="F")

array([[[-0.60854492,  0.46916285, -0.08461721, -0.03512837,
          1.65916458],
        [ 0.3732861 , -0.26228621,  0.728369  ,  0.23094248,
         -1.6412629 ]],

       [[-2.11961816, -0.64694338, -0.13860586, -0.43262796,
          1.06048937],
        [ 0.573722  ,  0.60064174, -0.72423121, -0.40414751,
          1.63503788]]])

In [5]:
x.reshape((2,2,-1))

array([[[-0.60854492,  0.46916285, -0.08461721, -0.03512837,
          1.65916458],
        [-2.11961816, -0.64694338, -0.13860586, -0.43262796,
          1.06048937]],

       [[ 0.3732861 , -0.26228621,  0.728369  ,  0.23094248,
         -1.6412629 ],
        [ 0.573722  ,  0.60064174, -0.72423121, -0.40414751,
          1.63503788]]])

In [6]:
x

array([[-0.60854492,  0.46916285, -0.08461721, -0.03512837,  1.65916458],
       [-2.11961816, -0.64694338, -0.13860586, -0.43262796,  1.06048937],
       [ 0.3732861 , -0.26228621,  0.728369  ,  0.23094248, -1.6412629 ],
       [ 0.573722  ,  0.60064174, -0.72423121, -0.40414751,  1.63503788]])

In [7]:
x.ravel()

array([-0.60854492,  0.46916285, -0.08461721, -0.03512837,  1.65916458,
       -2.11961816, -0.64694338, -0.13860586, -0.43262796,  1.06048937,
        0.3732861 , -0.26228621,  0.728369  ,  0.23094248, -1.6412629 ,
        0.573722  ,  0.60064174, -0.72423121, -0.40414751,  1.63503788])

In [8]:
x.flatten()

array([-0.60854492,  0.46916285, -0.08461721, -0.03512837,  1.65916458,
       -2.11961816, -0.64694338, -0.13860586, -0.43262796,  1.06048937,
        0.3732861 , -0.26228621,  0.728369  ,  0.23094248, -1.6412629 ,
        0.573722  ,  0.60064174, -0.72423121, -0.40414751,  1.63503788])

## Concatenate

In [9]:
x = [[1,3,5],[7,9,0]]
y = [[11,13,15],[17,19,10]]
arr1 = np.array(x)
arr2 = np.array(y)

In [10]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [11]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [12]:
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [13]:
np.vstack((arr1,arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

## Split

In [14]:
x = np.array([ 1,  4,  5,  6,  8,  9,  1,  4])
x

array([1, 4, 5, 6, 8, 9, 1, 4])

In [15]:
np.split(x,[2,5])

[array([1, 4]), array([5, 6, 8]), array([9, 1, 4])]

In [16]:
x = np.array([[ 1,  4,  5,  6,  8,  9,  1,  4],[ 1,  4,  5,  6,  8,  9,  1,  4]])
x

array([[1, 4, 5, 6, 8, 9, 1, 4],
       [1, 4, 5, 6, 8, 9, 1, 4]])

In [17]:
np.split(x,[4,6],axis=1)

[array([[1, 4, 5, 6],
        [1, 4, 5, 6]]),
 array([[8, 9],
        [8, 9]]),
 array([[1, 4],
        [1, 4]])]

In [18]:
np.split(x,[1],axis=0)

[array([[1, 4, 5, 6, 8, 9, 1, 4]]), array([[1, 4, 5, 6, 8, 9, 1, 4]])]

## Tile & Repeat

In [19]:
x = np.array([1,5,7,8])
np.repeat(x,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [20]:
x = np.array([1,5,7,8])
np.tile(x,3)

array([1, 5, 7, 8, 1, 5, 7, 8, 1, 5, 7, 8])