# Fancy Indexing Equivalents: take and put

In [1]:
import numpy as np
arr = np.arange(10) * 100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [2]:
inds = [7, 1, 2, 6]
inds

[7, 1, 2, 6]

In [3]:
arr[inds]

array([700, 100, 200, 600])

In [4]:
arr.take(inds)

array([700, 100, 200, 600])

In [5]:
arr.put(inds,42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [6]:
arr.put(inds, [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [7]:
arr = np.random.randn(2, 4)
arr

array([[-0.24258498, -1.51975705, -0.65826968,  0.26788072],
       [ 1.06119689,  1.25726596, -0.29556505, -0.75359794]])

In [8]:
inds = [2, 0, 2, 1]
inds

[2, 0, 2, 1]

In [9]:
arr.take(inds, axis=1)

array([[-0.65826968, -0.24258498, -0.65826968, -1.51975705],
       [-0.29556505,  1.06119689, -0.29556505,  1.25726596]])