# Repeating Elements: tile and repeat

In [1]:
import numpy as np

In [2]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [3]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [4]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [5]:
arr = np.random.randn(2, 2)
arr

array([[-0.7242146 ,  0.24148335],
       [-0.97723005, -1.60004621]])

In [6]:
arr.repeat(2)

array([-0.7242146 , -0.7242146 ,  0.24148335,  0.24148335, -0.97723005,
       -0.97723005, -1.60004621, -1.60004621])

In [7]:
arr.repeat(2, axis=0)

array([[-0.7242146 ,  0.24148335],
       [-0.7242146 ,  0.24148335],
       [-0.97723005, -1.60004621],
       [-0.97723005, -1.60004621]])

In [8]:
arr.repeat(2, axis=1)

array([[-0.7242146 , -0.7242146 ,  0.24148335,  0.24148335],
       [-0.97723005, -0.97723005, -1.60004621, -1.60004621]])

In [9]:
arr.repeat([2, 3], axis=0)

array([[-0.7242146 ,  0.24148335],
       [-0.7242146 ,  0.24148335],
       [-0.97723005, -1.60004621],
       [-0.97723005, -1.60004621],
       [-0.97723005, -1.60004621]])

In [10]:
arr.repeat([2, 3], axis=1)

array([[-0.7242146 , -0.7242146 ,  0.24148335,  0.24148335,  0.24148335],
       [-0.97723005, -0.97723005, -1.60004621, -1.60004621, -1.60004621]])

In [11]:
arr = np.arange(4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [12]:
np.tile(arr, 2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [13]:
np.tile(arr, (2, 1))

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [14]:
np.tile(arr, (3, 2))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])