# Concatenating and Splitting Arrays

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [3]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [5]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [7]:
#######################

In [8]:
arr = np.random.randn(7, 2)

In [9]:
arr

array([[ 1.82646076,  0.14445174],
       [-0.00916548,  0.68369998],
       [-1.05092531,  1.05809939],
       [ 0.31844993, -0.8447828 ],
       [-0.64948821,  0.41283262],
       [-2.88168409, -0.97959979],
       [-0.46573228, -0.17263956]])

In [10]:
first, second, third = np.split(arr, [1, 3])

In [11]:
first

array([[1.82646076, 0.14445174]])

In [12]:
second

array([[-0.00916548,  0.68369998],
       [-1.05092531,  1.05809939]])

In [13]:
third

array([[ 0.31844993, -0.8447828 ],
       [-0.64948821,  0.41283262],
       [-2.88168409, -0.97959979],
       [-0.46573228, -0.17263956]])

![](./snaps/a2.PNG)

In [14]:
arr = np.arange(6)

In [15]:
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)

In [16]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
arr2

array([[0.53152702, 1.24445869],
       [1.03685121, 0.02568228],
       [0.14720833, 0.30061136]])

In [18]:
np.r_[arr1, arr2]

array([[0.        , 1.        ],
       [2.        , 3.        ],
       [4.        , 5.        ],
       [0.53152702, 1.24445869],
       [1.03685121, 0.02568228],
       [0.14720833, 0.30061136]])

In [19]:
np.c_[np.r_[arr1, arr2], arr]

array([[0.        , 1.        , 0.        ],
       [2.        , 3.        , 1.        ],
       [4.        , 5.        , 2.        ],
       [0.53152702, 1.24445869, 3.        ],
       [1.03685121, 0.02568228, 4.        ],
       [0.14720833, 0.30061136, 5.        ]])

In [20]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])