# C Versus Fortran Order

In [1]:
import numpy as np

In [2]:
arr = np.arange(12).reshape((3, 4))

In [3]:
arr.ravel('C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
arr.ravel('A')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr.ravel('K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])