## 4.3.4 Sorting

###### Example01

In [1]:
import numpy as np
arr = np.random.randn(6)
arr

array([-0.63790367, -0.73028793, -0.84238712, -0.03024457,  0.51627719,
       -0.83303828])

In [2]:
arr.sort()
arr

array([-0.84238712, -0.83303828, -0.73028793, -0.63790367, -0.03024457,
        0.51627719])

###### Example02

In [3]:
arr = np.random.randn(5, 3)
arr

array([[ 1.11183973, -0.11514468,  1.05938865],
       [ 0.34703351, -0.14492475, -1.50926316],
       [ 0.29503416,  0.41633832, -0.1052305 ],
       [-0.36332075, -0.61797267, -0.30010487],
       [ 0.00435604, -1.27184466,  0.41533252]])

In [4]:
arr.sort(1)

In [5]:
arr

array([[-0.11514468,  1.05938865,  1.11183973],
       [-1.50926316, -0.14492475,  0.34703351],
       [-0.1052305 ,  0.29503416,  0.41633832],
       [-0.61797267, -0.36332075, -0.30010487],
       [-1.27184466,  0.00435604,  0.41533252]])

###### Example03

In [6]:
large_arr = np.random.randn(1000)
large_arr.sort()

In [7]:
large_arr[int(0.05 * len(large_arr))]

-1.7360153241350638