## 4.1.6 Fancy Indexing

In [1]:
import numpy as np

In [2]:
arr = np.empty((8, 4))

In [3]:
arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69118787e-306],
       [6.23058028e-307, 2.22526399e-307, 6.23053614e-307,
        7.56592338e-307],
       [1.60216183e-306, 7.56602523e-307, 3.56043054e-307,
        1.37961641e-306],
       [2.22518251e-306, 1.33511969e-306, 6.23036978e-307,
        6.23053954e-307],
       [9.34609790e-307, 8.45593934e-307, 9.34600963e-307,
        1.86921143e-306],
       [6.23061763e-307, 8.90104239e-307, 6.89804132e-307,
        1.33512376e-306],
       [6.89806849e-307, 9.34609790e-307, 1.69121096e-306,
        1.05700515e-307],
       [2.04712906e-306, 7.56589622e-307, 1.11258277e-307,
        8.90111708e-307]])

In [4]:
for i in range(8):
    arr[i]=i

In [5]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [6]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [7]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [8]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [9]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [10]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])