## 4.2 Universal Functions: Fast Element-Wise Array Functions

* A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays

In [1]:
import numpy as np

#### Uniary Universal Functions
![](./snaps/four.PNG)

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.abs(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.fabs(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
np.log(arr)

C:\Users\Hassan\AppData\Local\Temp\ipykernel_5004\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [9]:
np.log10(arr)

C:\Users\Hassan\AppData\Local\Temp\ipykernel_5004\2153533263.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [10]:
np.log2(arr)

C:\Users\Hassan\AppData\Local\Temp\ipykernel_5004\1405652587.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [11]:
np.log1p(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [12]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.ceil(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
np.floor(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
np.rint(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
np.modf(arr)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [17]:
np.isnan(arr)

array([False, False, False, False, False, False, False, False, False,
       False])

In [18]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [19]:
np.isinf(arr)

array([False, False, False, False, False, False, False, False, False,
       False])

In [20]:
# cos
# cosh
# sin
# sinh
# tan
# tanh
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [21]:
# arccos
# arccosh
# arcsin
# arcsinh
# arctan
# arctanh
np.arccos(arr)

C:\Users\Hassan\AppData\Local\Temp\ipykernel_5004\415676749.py:7: RuntimeWarning: invalid value encountered in arccos
  np.arccos(arr)


array([1.57079633, 0.        ,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan])

In [22]:
np.logical_not(arr)

array([ True, False, False, False, False, False, False, False, False,
       False])

#### Binary Uniary functions
![](snaps/four1.PNG)
![](snaps/four2.PNG)

In [23]:
x = np.random.randn(8)
y = np.random.randn(8)

In [24]:
x

array([ 0.08343565,  3.62149988, -0.8481895 ,  1.35534822,  0.15871813,
       -1.3291815 , -0.28176699, -1.2392097 ])

In [25]:
y

array([-0.07428956,  0.0402246 ,  0.22600837,  0.13785277,  0.00774745,
       -1.9253059 , -1.37296725, -1.63402135])

In [26]:
np.add(x,y)

array([ 0.00914609,  3.66172449, -0.62218113,  1.49320099,  0.16646558,
       -3.2544874 , -1.65473424, -2.87323105])

In [27]:
np.subtract(x,y)

array([ 0.15772522,  3.58127528, -1.07419788,  1.21749544,  0.15097067,
        0.5961244 ,  1.09120026,  0.39481165])

In [28]:
np.multiply(x,y)

array([-6.19839815e-03,  1.45673399e-01, -1.91697928e-01,  1.86838508e-01,
        1.22966107e-03,  2.55908098e+00,  3.86856851e-01,  2.02489510e+00])

In [29]:
np.divide(x,y)

array([-1.12311402, 90.03195844, -3.75291189,  9.83185321, 20.4864933 ,
        0.69037419,  0.20522484,  0.75838036])

In [30]:
np.floor_divide(x,y)

array([-2., 90., -4.,  9., 20.,  0.,  0.,  0.])

In [31]:
np.power(x,y)

C:\Users\Hassan\AppData\Local\Temp\ipykernel_5004\202835073.py:1: RuntimeWarning: invalid value encountered in power
  np.power(x,y)


array([1.20263078, 1.05312778,        nan, 1.04280614, 0.98584104,
              nan,        nan,        nan])

In [32]:
np.maximum(x,y)

array([ 0.08343565,  3.62149988,  0.22600837,  1.35534822,  0.15871813,
       -1.3291815 , -0.28176699, -1.2392097 ])

In [33]:
np.fmax(x,y)

array([ 0.08343565,  3.62149988,  0.22600837,  1.35534822,  0.15871813,
       -1.3291815 , -0.28176699, -1.2392097 ])

In [34]:
np.minimum(x,y)

array([-0.07428956,  0.0402246 , -0.8481895 ,  0.13785277,  0.00774745,
       -1.9253059 , -1.37296725, -1.63402135])

In [35]:
np.fmin(x,y)

array([-0.07428956,  0.0402246 , -0.8481895 ,  0.13785277,  0.00774745,
       -1.9253059 , -1.37296725, -1.63402135])

In [36]:
np.mod(x,y)

array([-6.51434772e-02,  1.28551549e-03,  5.58439803e-02,  1.14673271e-01,
        3.76908351e-03, -1.32918150e+00, -2.81766991e-01, -1.23920970e+00])

In [37]:
np.copysign(x,y)

array([-0.08343565,  3.62149988,  0.8481895 ,  1.35534822,  0.15871813,
       -1.3291815 , -0.28176699, -1.2392097 ])

In [38]:
np.greater(x,y)

array([ True,  True, False,  True,  True,  True,  True,  True])

In [39]:
np.greater_equal(x,y)

array([ True,  True, False,  True,  True,  True,  True,  True])

In [40]:
np.less(x,y)

array([False, False,  True, False, False, False, False, False])

In [41]:
np.less_equal(x,y)

array([False, False,  True, False, False, False, False, False])

In [42]:
np.equal(x,y)

array([False, False, False, False, False, False, False, False])

In [43]:
np.not_equal(x,y)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [44]:
np.logical_and(x,y)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [45]:
np.logical_or(x,y)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [46]:
np.logical_xor(x,y)

array([False, False, False, False, False, False, False, False])