## 4.5 Linear Algebra

In [1]:
import numpy as np

![](snaps/ten.PNG)

###### Example01

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [4]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [5]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [7]:
x @ np.ones(3)

array([ 6., 15.])

In [8]:
######

In [9]:
ar1 = np.arange(9)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
ar2 = np.array([[9., 10.,11.], [12., 13., 14.],[15., 16., 17.]])
ar2

array([[ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.]])

In [11]:
np.diag(ar1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8]])

In [12]:
np.diag(ar2)

array([ 9., 13., 17.])

In [13]:
######

In [14]:
ar2

array([[ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.]])

In [15]:
np.trace(ar2)

39.0

In [16]:
from numpy.linalg import det,eig
det(ar2)

0.0

In [17]:
eig(ar2)

(array([ 3.94562020e+01, -4.56202043e-01,  4.23539028e-16]),
 array([[-0.43812234, -0.74152183,  0.40824829],
        [-0.56759026, -0.03577375, -0.81649658],
        [-0.69705818,  0.66997434,  0.40824829]]))

###### Example02

In [18]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)


array([[ 1.73804007,  0.19456701, -0.36519702,  0.06368788, -2.27168505],
       [ 0.19456701,  0.32288726,  0.11043651, -0.0918067 , -0.24736996],
       [-0.36519702,  0.11043651,  0.36984718, -0.13197103,  0.53078522],
       [ 0.06368788, -0.0918067 , -0.13197103,  0.14389239, -0.07318106],
       [-2.27168505, -0.24736996,  0.53078522, -0.07318106,  3.1881201 ]])

In [19]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  0.00000000e+00,  4.44089210e-16,
        -1.11022302e-16, -2.55351296e-15],
       [-3.33066907e-16,  1.00000000e+00, -1.24900090e-16,
         9.54097912e-17,  4.44089210e-16],
       [ 0.00000000e+00, -1.11022302e-16,  1.00000000e+00,
         1.52655666e-16, -2.77555756e-16],
       [ 0.00000000e+00,  5.55111512e-17,  0.00000000e+00,
         1.00000000e+00,  2.22044605e-16],
       [ 3.55271368e-15,  6.66133815e-16, -4.44089210e-16,
         5.55111512e-17,  1.00000000e+00]])

In [20]:
q, r = qr(mat)
q

array([[-0.79640311, -0.00999501, -0.19071203, -0.002452  , -0.57381625],
       [ 0.06620103, -0.87590328, -0.04860285,  0.4713219 , -0.06248441],
       [ 0.0747858 ,  0.33840861, -0.74063661,  0.55979315,  0.13407368],
       [ 0.17301438, -0.31456391, -0.64168362, -0.6775072 , -0.01848517],
       [-0.57081749, -0.13864599, -0.03108436, -0.07392755,  0.80530315]])

In [21]:
r

array([[-11.00412045,   0.98284605,   2.69343755,   4.96006557,
         -8.27830822],
       [  0.        ,  -5.42846553,   2.60922664,  -3.75766948,
         -0.98535009],
       [  0.        ,   0.        ,  -7.06924128, -10.47166228,
          0.92682741],
       [  0.        ,   0.        ,   0.        ,  -4.77597842,
         -0.13281768],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.25259498]])