## 4.4 File Input and Output with Arrays

In [1]:
import numpy as np

###### Example01

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('files/some_array', arr)

In [4]:
np.load('files/some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### Example02

In [5]:
np.savez('files/array_archive.npz', a=arr, b=arr)

In [6]:
arch = np.load('files/array_archive.npz')
arch

In [7]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.savez_compressed('files/arrays_compressed.npz', a=arr, b=arr)