## 4.1.5 Boolean Indexing

In [1]:
import numpy as np

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
data = np.random.randn(7, 4)
data

array([[-0.67136077, -0.32331083,  0.29232074, -0.8852759 ],
       [-0.87945322,  0.08246367, -0.72225934, -0.59085583],
       [ 0.07704023,  0.46711354, -0.42658118,  0.32519545],
       [-0.65625752,  0.73787197,  2.11842661, -0.91845614],
       [ 2.06682534, -0.5659189 , -0.4185846 ,  0.57889561],
       [ 0.58886923,  1.60526775,  0.14969896,  0.75381419],
       [-0.47318325, -0.357671  , -0.10623932, -0.23659396]])

In [4]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [5]:
data[names == 'Bob']

array([[-0.67136077, -0.32331083,  0.29232074, -0.8852759 ],
       [-0.65625752,  0.73787197,  2.11842661, -0.91845614]])

In [6]:
data[names == 'Bob', 2:]

array([[ 0.29232074, -0.8852759 ],
       [ 2.11842661, -0.91845614]])

In [7]:
data[names == 'Bob', 3]

array([-0.8852759 , -0.91845614])

In [8]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [9]:
data[~(names == 'Bob')]

array([[-0.87945322,  0.08246367, -0.72225934, -0.59085583],
       [ 0.07704023,  0.46711354, -0.42658118,  0.32519545],
       [ 2.06682534, -0.5659189 , -0.4185846 ,  0.57889561],
       [ 0.58886923,  1.60526775,  0.14969896,  0.75381419],
       [-0.47318325, -0.357671  , -0.10623932, -0.23659396]])

In [10]:
cond = names == 'Bob'
data[~cond]

array([[-0.87945322,  0.08246367, -0.72225934, -0.59085583],
       [ 0.07704023,  0.46711354, -0.42658118,  0.32519545],
       [ 2.06682534, -0.5659189 , -0.4185846 ,  0.57889561],
       [ 0.58886923,  1.60526775,  0.14969896,  0.75381419],
       [-0.47318325, -0.357671  , -0.10623932, -0.23659396]])

In [11]:
mask = (names == 'Bob') | (names == 'Will')

In [12]:
mask

array([ True, False,  True,  True,  True, False, False])

In [13]:
data[mask]

array([[-0.67136077, -0.32331083,  0.29232074, -0.8852759 ],
       [ 0.07704023,  0.46711354, -0.42658118,  0.32519545],
       [-0.65625752,  0.73787197,  2.11842661, -0.91845614],
       [ 2.06682534, -0.5659189 , -0.4185846 ,  0.57889561]])

In [14]:
data[data < 0] = 0

In [15]:
data

array([[0.        , 0.        , 0.29232074, 0.        ],
       [0.        , 0.08246367, 0.        , 0.        ],
       [0.07704023, 0.46711354, 0.        , 0.32519545],
       [0.        , 0.73787197, 2.11842661, 0.        ],
       [2.06682534, 0.        , 0.        , 0.57889561],
       [0.58886923, 1.60526775, 0.14969896, 0.75381419],
       [0.        , 0.        , 0.        , 0.        ]])

In [16]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.08246367, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.58886923, 1.60526775, 0.14969896, 0.75381419],
       [0.        , 0.        , 0.        , 0.        ]])