## 4.1.7 Transposing Arrays and Swapping Axes

In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [4]:
arr = np.random.randn(6, 3)
arr

array([[-0.37106329,  1.72536292,  0.84726152],
       [-1.37644121, -0.8516072 ,  0.81196235],
       [ 0.40859896,  0.84418675,  0.12686013],
       [-0.05913559, -0.83007015, -1.90728637],
       [ 0.20870561, -0.04665996,  0.60276117],
       [ 0.24976911, -0.56703927,  0.98166191]])

In [5]:
np.dot(arr.T, arr)

array([[ 2.30867114,  0.77462184, -0.89639419],
       [ 0.77462184,  5.42749043,  1.87587009],
       [-0.89639419,  1.87587009,  6.35795087]])

In [6]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [7]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [8]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])