### 4.3.1 Expressing Conditional Logic as Array Operations

###### Example01

In [1]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [2]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [3]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

###### Example02

In [4]:
arr = np.random.randn(4, 4)
arr

array([[ 0.82511413,  0.62536165, -0.17902665, -1.08153667],
       [-0.1403486 ,  1.11815563,  0.01928003, -0.85256519],
       [-0.95433754, -1.26618331, -1.31316084, -0.02164461],
       [-0.13545581,  0.58353088, -0.42839465,  0.62942327]])

In [5]:
arr > 0

array([[ True,  True, False, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [False,  True, False,  True]])

In [6]:
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2, -2],
       [-2,  2,  2, -2],
       [-2, -2, -2, -2],
       [-2,  2, -2,  2]])

In [7]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        , -0.17902665, -1.08153667],
       [-0.1403486 ,  2.        ,  2.        , -0.85256519],
       [-0.95433754, -1.26618331, -1.31316084, -0.02164461],
       [-0.13545581,  2.        , -0.42839465,  2.        ]])