## 4.1.1 Creating ndArrays

In [1]:
import numpy as np

## Creating ndArrays

![](./snaps/one.PNG)

#### array

In [2]:
# One dimesional Array
data1 = [6, 7.5, 8, 0, 1]
print(data1)
arr1 = np.array(data1)
arr1

[6, 7.5, 8, 0, 1]


array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
# Multidimesional Array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(data2)
arr2 = np.array(data2)
arr2

[[1, 2, 3, 4], [5, 6, 7, 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# Dimensions of the nd array
arr2.ndim

2

In [5]:
# Shape of the nd array
arr2.shape

(2, 4)

In [6]:
# Data type of arrays
arr1.dtype

dtype('float64')

In [7]:
arr2.dtype

dtype('int32')

#### asarray

In [8]:
data3 = [6, 7.5, 8, 0, 1]
print(data3)
arr3 = np.asarray(data3)
arr3

[6, 7.5, 8, 0, 1]


array([6. , 7.5, 8. , 0. , 1. ])

#### arange

In [9]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### ones and ones_like

In [10]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
data4 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr4 = np.array(data4)
print(arr4)
np.ones_like(arr4)

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#### zeos and zeros_like

In [13]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.zeros_like(arr4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### empty and empty_like

In [16]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.empty_like(arr4)

array([[      0,       1,       0, 5570652],
       [    472,       0,     768,       0]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### full and full_like

In [19]:
np.full((2, 3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [20]:
np.full_like(arr4,26)

array([[26, 26, 26, 26],
       [26, 26, 26, 26]])

#### eye, identity

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])