## 4.1.4 Basic Indexing and Slicing

In [1]:
import numpy as np

###### Exampe01

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

* if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcasted henceforth) to the entire selection. 
* An important first distinction from Python’s built-in lists is that array slices are views on the original array.
* This means that the data is not copied, and any modifications to the view will be reflected in the source array

In [8]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [9]:
arr_slice[1] = 12345

In [10]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [11]:
arr_slice[:] = 64

In [12]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

* to copy slice of an ndarray use .copy()

###### Example02

In [13]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [14]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr2d[2]

array([7, 8, 9])

In [16]:
arr2d[2][2]

9

In [17]:
arr2d[2, 2]

9

![](./snaps/three1.PNG)

###### Example03

In [18]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [19]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
old_values = arr3d[0].copy()

In [22]:
arr3d[0] = 42

In [23]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3d[0] = old_values

In [25]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
arr3d[1, 0]

array([7, 8, 9])

In [27]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [28]:
x[0]

array([7, 8, 9])

#### Indexing with slices

###### Exapmle04

In [29]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [30]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

###### Exapmle05

In [31]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [34]:
arr2d[1, :2]

array([4, 5])

In [35]:
arr2d[:2, 2]

array([3, 6])

In [36]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [37]:
arr2d[:2, 1:] = 0

In [38]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

![](./snaps/three2.PNG)

![](three.png)

![](four.png)