## 4.1.0 The NumPy ndarray: A Multidimensional Array Object
* numPy store data in the form of mattrix and can perform operation on multiple datasets same as scalor

In [1]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 0.0327482 , -1.49713371,  0.90887221],
       [-0.36139917, -0.64310155, -1.19135931]])

In [2]:
data * 10

array([[  0.32748198, -14.97133706,   9.08872215],
       [ -3.61399169,  -6.43101547, -11.91359315]])

In [3]:
data + data

array([[ 0.0654964 , -2.99426741,  1.81774443],
       [-0.72279834, -1.28620309, -2.38271863]])

* An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type.
* Every array has a shape, a tuple indicating the size of each dimension a dtype, an object describing the data type of the array

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')