## 4.1.2 Data Types for ndarrays

In [1]:
import numpy as np

#### 4.1.2 Data Types for ndarrays

In [2]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [3]:
arr1.dtype

dtype('float64')

In [4]:
arr2.dtype

dtype('int32')

![](./snaps/two.png)

#### DataType conversion

###### Example01

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int32')

In [7]:
float_arr = arr.astype(np.float64)

In [8]:
float_arr

array([1., 2., 3., 4., 5.])

In [9]:
float_arr.dtype

dtype('float64')

###### Example02

In [10]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [11]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

###### Example03

In [12]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings)
numeric_strings.astype(float)

[b'1.25' b'-9.6' b'42']


array([ 1.25, -9.6 , 42.  ])

In [ ]:
## Example

In [13]:
int_array = np.arange(10)
print(int_array)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [15]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [16]:
int_array.astype(calibers.dtype)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
# Example

In [18]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([  0,   1,   0, 606, 752,   0, 768,   0], dtype=uint32)