## 4.3.2 Mathematical and Statistical Methods

![](snaps/five.PNG)

In [1]:
import numpy as np
arr = np.random.randn(5, 4)
arr

array([[ 2.08604092, -0.33141796,  1.44418606,  0.47898519],
       [-2.25657693, -1.04843013,  0.58547553,  0.60962215],
       [-0.9912183 ,  0.50347386,  1.43458283, -0.16631044],
       [-1.14479471, -2.84801408,  1.56651766, -0.02410039],
       [ 0.10751645, -0.00505128,  0.05716156, -0.55902786]])

In [2]:
arr.sum()

-0.5013798688614204

In [3]:
arr.sum(axis=0)

array([-2.19903257, -3.7294396 ,  5.08792364,  0.33916866])

In [4]:
arr.sum(axis=1)

array([ 3.67779421, -2.10990938,  0.78052796, -2.45039152, -0.39940113])

In [5]:
arr.mean()

-0.02506899344307102

In [6]:
arr.mean(axis=0)

array([-0.43980651, -0.74588792,  1.01758473,  0.06783373])

In [7]:
arr.mean(axis=1)

array([ 0.91944855, -0.52747734,  0.19513199, -0.61259788, -0.09985028])

In [8]:
# std
arr.var()

1.4597525374294305

In [9]:
# max
arr.min()

-2.8480140831163117

In [10]:
arr.min(axis=0)

array([-2.25657693, -2.84801408,  0.05716156, -0.55902786])

In [11]:
arr.min(axis=1)

array([-0.33141796, -2.25657693, -0.9912183 , -2.84801408, -0.55902786])

In [12]:
arr.argmin()

13

In [13]:
arr.argmax()

0

###### example02

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [15]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [17]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [18]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])