# NumPy Muhammad Qasim 2020/12/20

In [1]:
print("Helloworld")

Helloworld


In [2]:
print("Line1")
print("Line2")

Line1
Line2


In [3]:
%history

print("Helloworld")
print("Line1")
print("Line2")
%history


In [4]:
# %load abc.py
print("Line1")
print("Line2")
print("Line3")


Line1
Line2
Line3


In [5]:
%run abc.py

Line1
Line2
Line3


In [6]:
%time print("ada")

ada
CPU times: total: 0 ns
Wall time: 0 ns


In [7]:
%time %run abc.py

Line1
Line2
Line3
CPU times: total: 15.6 ms
Wall time: 4.99 ms


# Python

In [8]:
%time l1 = list(range(1,3000000))
print(l1[:10])

CPU times: total: 93.8 ms
Wall time: 112 ms
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
%time [x+5 for x in l1][:10]

CPU times: total: 453 ms
Wall time: 533 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [10]:
for i, e in list(enumerate(l1)):
    l1[i] = l1[i] + 5
l1[:10]    

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [11]:
for i, e in list(enumerate(l1)):
    l1[i] += 5
l1[:10]  

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [12]:
l1 = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print("Before Adding 5")
print(l1)
print()
for ri, rd in list(enumerate(l1)):
    for ci, cd in list(enumerate(rd)):
        l1[ri][ci] += 5
print("After Adding 5")
print(l1)

Before Adding 5
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

After Adding 5
[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


In [13]:
l1 = [1,2,4]
# Return an error
# l1 + 5

# Numpy 

In [14]:
def abc():print("pakistan") #python
def abc():print("Hello World") #Numpy
    
abc()

Hello World


In [15]:
#import numpy as *
import numpy as np

In [16]:
l = [1,3,2]
print(sum(l)) # python function
print(np.sum(l)) # Numpy function

6
6


In [17]:
l1 = np.arange(1,3_000_000)
%time l1 + 5

CPU times: total: 15.6 ms
Wall time: 15.6 ms


array([      6,       7,       8, ..., 3000002, 3000003, 3000004])

In [18]:
l1 = np.arange(1,13)

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Diminsion: 1
Type: int32
Size: 12
Itemsize: 4
Shape: (12,)


In [19]:
l1 = np.array(1) # scaler value

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize) # data is saving in 4 vyte
print("Shape:", l1.shape)

1
Diminsion: 0
Type: int32
Size: 1
Itemsize: 4
Shape: ()


In [20]:
l1 = np.array([1,2]) #1D

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize) # data is saving in 4 vyte
print("Shape:", l1.shape)

[1 2]
Diminsion: 1
Type: int32
Size: 2
Itemsize: 4
Shape: (2,)


In [21]:
l1 = np.array([[1,2],
               [3,4]])  #2D

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize) # data is saving in 4 vyte
print("Shape:", l1.shape)

[[1 2]
 [3 4]]
Diminsion: 2
Type: int32
Size: 4
Itemsize: 4
Shape: (2, 2)


# A Multidimensional Array Object

In [22]:
import numpy as np 

l1 = np.arange(1,13)
l1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
np.arange(1,13).reshape((2,-1))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [24]:
np.arange(1,13).reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.arange(1,13).reshape((12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [26]:
l1 = np.arange(1,13).reshape((4,3))
l1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
l1 = np.arange(1,13).reshape((3,4))
l1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
l1 = np.arange(1,13).reshape((2,6))
l1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [29]:
l1 = np.arange(1,13).reshape((6,2))
l1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [30]:
l1 = np.arange(1,13).reshape((12,1))
l1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [31]:
l1 = np.arange(1,13).reshape((2,-1))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Diminsion: 2
Type: int32
Size: 12
Itemsize: 4
Shape: (2, 6)


<img src="https://www.pythoninformer.com/img/numpy/3d-array-stack.png">
<img src="https://www.pythoninformer.com/img/numpy/3d-array.png">

In [32]:
# l1[i,j,k]
# l1[slide, row, column]

In [33]:
np.arange(3*2*3*2*2).reshape(3,2,3,2,2) 
# [no of videos , no of frames , 3 for rgb, row , column]
# # 3 videos ha 2 slides/frame ha 3 rgb k or 2 by 2 k ha 

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]],



       [[[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]],

         [[32, 33],
          [34, 35]]],


        [[[36, 37],
          [38, 39]],

         [[40, 41],
          [42, 43]],

         [[44, 45],
          [46, 47]]]],



       [[[[48, 49],
          [50, 51]],

         [[52, 53],
          [54, 55]],

         [[56, 57],
          [58, 59]]],


        [[[60, 61],
          [62, 63]],

         [[64, 65],
          [66, 67]],

         [[68, 69],
          [70, 71]]]]])

In [34]:
np.arange(4*3*2*2).reshape(4,3,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43]],

        [[44, 45],
         [46, 47]]]])

In [35]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Diminsion: 3
Type: int32
Size: 27
Itemsize: 4
Shape: (3, 3, 3)


In [36]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
# l1[i,j,k]
# l1[slide, row, column]
print("====")
print(l1[2])
print(l1[1,2])
print(l1[1,2,1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
====
[[19 20 21]
 [22 23 24]
 [25 26 27]]
[16 17 18]
17


In [37]:
l1[1][2][0]

16

In [38]:
# postive values ly awo jo k hum Deep learing main karty 
# k +ve value ly awo 

In [39]:
l1 = np.array(['a','b','c'])
print(l1)
#    0     1    2
print(l1[[True,True,False]])
print(l1[[True,False,True]])

['a' 'b' 'c']
['a' 'b']
['a' 'c']


In [40]:
ages = np.arange(1,50)
adult = []
for age in ages:
    if age >18:
        adult.append(True)
    else:
        adult.append(False)
adult

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [41]:
ages[adult]

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [42]:
ages[ages>32]

array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
l1 = np.arange(1,28).reshape((3,3,3))
l1[l1 % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [44]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print("***")
print(l1[l1 % 6 == 0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
***
[ 6 12 18 24]


In [45]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
l1[(l1 % 3 == 0) & (l1 % 9 == 0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 9, 18, 27])

In [46]:
l1 = np.random.randn(3,3,3)

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 1.41117691  0.77043057 -0.38518438]
  [-0.57185411  1.3091197   0.41115505]
  [ 0.82146531  0.53352058 -0.28247277]]

 [[ 0.03372132  0.00320585  0.6687832 ]
  [ 0.26715963  2.86608266 -0.64496015]
  [ 0.40143783  1.2705915  -1.23091397]]

 [[ 0.71082638 -1.70516825 -0.38272867]
  [-0.86292453 -1.24619121 -0.68549468]
  [-0.12667335  0.50916609 -1.0988388 ]]]
Diminsion: 3
Type: float64
Size: 27
Itemsize: 8
Shape: (3, 3, 3)


In [47]:
l1 = ((np.random.randn(3,3))*100).astype("int8")
l1

array([[ 79, -51,  84],
       [ 29,  60,  88],
       [-50, -73, 117]], dtype=int8)

In [48]:
print("*****")
print(l1 + 2)
print("*****")
print(l1 * 2)
print("*****")
print(l1 / 2)
print("*****")
print(l1 ** 2)
print("*****")
print(l1 ** 0.5)
print("*****")
print(l1 % 2)
print("*****")

*****
[[ 81 -49  86]
 [ 31  62  90]
 [-48 -71 119]]
*****
[[ -98 -102  -88]
 [  58  120  -80]
 [-100  110  -22]]
*****
[[ 39.5 -25.5  42. ]
 [ 14.5  30.   44. ]
 [-25.  -36.5  58.5]]
*****
[[  97   41 -112]
 [  73   16   64]
 [ -60  -47  121]]
*****
[[ 8.88819442         nan  9.16515139]
 [ 5.38516481  7.74596669  9.38083152]
 [        nan         nan 10.81665383]]
*****
[[1 1 0]
 [1 0 0]
 [0 1 1]]
*****


C:\Users\Hassan\AppData\Local\Temp\ipykernel_1204\1919663190.py:10: RuntimeWarning: invalid value encountered in power
  print(l1 ** 0.5)


# Creating ndarrays

##### np.array()

In [49]:
# Deep Copy(Always copy) # physical data naya bnae ga 
l = [1,2,3]

a = np.array(l)
b = np.array(a)

print(a is l) #False
print(b is a) #False
print(id(a) == id(a))
print(id(a) == id (b))

False
False
True
False


In [50]:
# 1 array->Same Datatype->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #3
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#2

print(l,a,b,c, sep = ' ')
print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
[1, 2, 3] [1 2 3] [1 2 3] [1. 2. 3.]
True
False
False


numpy.ndarray

In [51]:
import numpy as np
a = np.array([1,2])
a.itemsize

4

In [52]:
import numpy as np

## Creating ndarrays

In [53]:
a = np.array([1,3,4])
b = np.asarray([1,3,5])

In [54]:
print(a , b , sep = ' ')

[1 3 4] [1 3 5]


In [55]:
a = np.arange(1,14)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

# Chaining

In [56]:
def A(x):return x+5
def B(x):return x+6    
def C(x):return x+7    

In [57]:
C(B(A(1)))

19

In [58]:
A(B(C(1)))

19

np.A().B().C()

In [59]:
#arange().reshape()
#np.ones
#np.ones_like
#np.zeros
#np.zeros_like
#np.full
#np.full_like
#np.empty
#np.empty_like

In [60]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [61]:
b = np.reshape(a, (27,1))
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27]])

In [62]:
a = np.arange(1,28)
print(a)
print(a.ndim)
a.shape = (3,9) # becuase private ni ha to hu khud b change kar skty jase reshape main karty hain # IN MEMORY
a.reshape(3,3,3) # becuase of INLINE funstion didn't changes the shape
print(a.ndim)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1
2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [63]:
a = a.reshape(3,3,3) #Now it will be in in memory
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [64]:
a.shape = (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [65]:
a.shape

(9, 3)

In [66]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [67]:
np.zeros((a.shape[0], a.shape[1])) 
# jo array ya image dy uska trha k image  ya array bnao 
# jis k values zero hu

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
a.shape

(9, 3)

In [69]:
np.zeros((a.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.zeros(a.shape) # return in float

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.zeros_like(a) # return integers

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [72]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [73]:
b = np.ones((3,3)) # in float
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
b = np.ones_like(a) # in integer
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [75]:
b = np.ones_like(a) * 5 # + 5
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [76]:
b = np.full((3,3), 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [77]:
b = np.full_like(a, 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [78]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [79]:
np.full_like(a, dtype=a.dtype, fill_value=2.5)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [80]:
np.full_like(a, dtype=np.float64, fill_value=2.5)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [81]:
np.empty((3,9))

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

In [82]:
np.empty_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
np.full_like(a, 1) * np.nan


array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [84]:
np.full(a.shape, np.nan)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [85]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [86]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Data Types for ndarrays

In [87]:
a = np.array([1,3,4], dtype='int')
a.dtype

dtype('int32')

In [88]:
a = np.array([1,3,4], dtype=int)
a.dtype

dtype('int32')

In [89]:
a = np.array([1,3,4], dtype=np.int64)
a.dtype

dtype('int64')

In [90]:
a = np.array([1,3,4], dtype='i8')
a.dtype

dtype('int64')

In [91]:
b = np.array([3,8,9], dtype=a.dtype)
b.dtype

dtype('int64')

In [92]:
c = a.astype(np.int64)
c.dtype

dtype('int64')

# Boolen Operation

In [93]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [94]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [95]:
print(a)
a[a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [96]:
print(a)
a[(a%3==0) & (a%5==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([15])

In [97]:
print(a)
a[~a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [98]:
print(a)
a[~(a%3==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [99]:
print(a)
a[a%3!=0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [100]:
a = np.arange(1,7).reshape((2,3,1))
a

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

# Fancy Slicing

In [101]:
import numpy as np

In [102]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)
a[[1,2,0]]


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [103]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print()
print(a[[1,2,0]])
# print(a[[1,2,0]])
#a[[0,1,2],[0,1,2],]
# a[[1,2,0]][:,[2,1,0]]
#a[[1,2,0]][:,[-1,0]]
#a[[1,2,0],:,::-1]
#a[::-1]
#a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]

[[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [104]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print()
# print(a[[1,2,0]])
print(a[[1,2,0]])
#a[[0,1,2],[0,1,2],]
# a[[1,2,0]][:,[2,1,0]]
#a[[1,2,0]][:,[-1,0]]
#a[[1,2,0],:,::-1]
#a[::-1]
#a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]

[[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [105]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print()
# print(a[[1,2,0]])
# print(a[[1,2,0]])
a[[0,1,2],[0,1,2],]
# a[[1,2,0]][:,[2,1,0]]
#a[[1,2,0]][:,[-1,0]]
#a[[1,2,0],:,::-1]
#a[::-1]
#a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]



array([[10, 11, 12],
       [22, 23, 24],
       [34, 35, 36]])

In [106]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print()
# print(a[[1,2,0]])
# print(a[[1,2,0]])
#a[[0,1,2],[0,1,2],]
a[[1,2,0]][:,[2,1,0]]
#a[[1,2,0]][:,[-1,0]]
#a[[1,2,0],:,::-1]
#a[::-1]
#a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]



array([[[25, 26, 27],
        [22, 23, 24],
        [19, 20, 21]],

       [[34, 35, 36],
        [31, 32, 33],
        [28, 29, 30]],

       [[16, 17, 18],
        [13, 14, 15],
        [10, 11, 12]]])

In [107]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print()
# print(a[[1,2,0]])
# print(a[[1,2,0]])
#a[[0,1,2],[0,1,2],]
# a[[1,2,0]][:,[2,1,0]]
a[[1,2,0]][:,[-1,0]]
#a[[1,2,0],:,::-1]
#a[::-1]
#a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]



array([[[25, 26, 27],
        [19, 20, 21]],

       [[34, 35, 36],
        [28, 29, 30]],

       [[16, 17, 18],
        [10, 11, 12]]])

In [108]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print()
# print(a[[1,2,0]])
# print(a[[1,2,0]])
#a[[0,1,2],[0,1,2],]
# a[[1,2,0]][:,[2,1,0]]
#a[[1,2,0]][:,[-1,0]]
a[[1,2,0],:,::-1]
#a[::-1]
#a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]



array([[[21, 20, 19],
        [24, 23, 22],
        [27, 26, 25]],

       [[30, 29, 28],
        [33, 32, 31],
        [36, 35, 34]],

       [[12, 11, 10],
        [15, 14, 13],
        [18, 17, 16]]])

In [109]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print()
# print(a[[1,2,0]])
# print(a[[1,2,0]])
#a[[0,1,2],[0,1,2],]
# a[[1,2,0]][:,[2,1,0]]
#a[[1,2,0]][:,[-1,0]]
#a[[1,2,0],:,::-1]
a[::-1]
#a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]



array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [110]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print()
# print(a[[1,2,0]])
# print(a[[1,2,0]])
#a[[0,1,2],[0,1,2],]
# a[[1,2,0]][:,[2,1,0]]
#a[[1,2,0]][:,[-1,0]]
#a[[1,2,0],:,::-1]
#a[::-1]
a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]



array([[[16, 17, 18],
        [13, 14, 15],
        [10, 11, 12]],

       [[25, 26, 27],
        [22, 23, 24],
        [19, 20, 21]],

       [[34, 35, 36],
        [31, 32, 33],
        [28, 29, 30]]])

In [111]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-0.16159695  0.44384071  1.48942813  0.18835244]
 [ 0.65696301 -1.26554175 -0.53924994  1.58998032]
 [ 1.12614845  0.56933796  1.74145008 -0.53432974]
 [ 0.56416225  1.15331436  0.92646836  0.19622826]
 [ 1.49327826  0.54488363 -1.80304261 -0.56274493]
 [ 0.24117658 -0.58786297  0.12958648 -0.06272342]]


In [112]:
names == "Qasim"

array([ True, False, False, False,  True, False])

In [113]:
data[[ True, False, False, False,  True, False]]

array([[-0.16159695,  0.44384071,  1.48942813,  0.18835244],
       [ 1.49327826,  0.54488363, -1.80304261, -0.56274493]])

In [114]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

print()
data[names=="Qasim"]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[ 0.03901501  1.58692754 -0.35550031 -0.26076359]
 [-0.64835814 -0.23579932  0.23616471 -0.7090441 ]
 [-1.81269017  0.12459225  1.12444413 -1.29111733]
 [-0.72386945 -0.56734752  0.31707338  0.64561365]
 [ 0.88157552 -0.78954985  0.98449857 -0.60451316]
 [ 1.52433917  0.98839515  1.27330846  2.05249076]]



array([[ 0.03901501,  1.58692754, -0.35550031, -0.26076359],
       [ 0.88157552, -0.78954985,  0.98449857, -0.60451316]])

In [115]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-1.58608622 -2.47543984  1.27298132  1.6716481 ]
 [-0.70102909  1.05973152  0.24903905 -1.66765501]
 [ 0.46757554 -1.97038881  0.25175673  2.00543108]
 [-0.81944554  0.63987915  0.25255936  0.66464455]
 [-1.02435447  0.11669802 -0.86942869 -0.76074596]
 [-0.85939715 -0.54989783 -2.73566145 -0.67447632]]


array([[-1.58608622, -2.47543984,  1.27298132,  1.6716481 ],
       [-0.81944554,  0.63987915,  0.25255936,  0.66464455],
       [-1.02435447,  0.11669802, -0.86942869, -0.76074596]])

In [116]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names!="Qasim") |  (names!="Ali")]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-1.05290582  1.09490524  0.43929247 -0.07059709]
 [-0.90655519 -0.44603586  2.2190807  -1.00966796]
 [ 0.71452682  1.50082815 -2.48403712 -0.6885078 ]
 [-1.88903563  1.52718442 -1.98166222 -1.16392484]
 [ 0.22927698 -0.87293561  0.73270019 -2.17059421]
 [ 0.25112446 -0.96617111 -0.084067    0.22974815]]


array([[-1.05290582,  1.09490524,  0.43929247, -0.07059709],
       [-0.90655519, -0.44603586,  2.2190807 , -1.00966796],
       [ 0.71452682,  1.50082815, -2.48403712, -0.6885078 ],
       [-1.88903563,  1.52718442, -1.98166222, -1.16392484],
       [ 0.22927698, -0.87293561,  0.73270019, -2.17059421],
       [ 0.25112446, -0.96617111, -0.084067  ,  0.22974815]])

In [117]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")][:,[0,-1]]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[ 0.55467126 -0.54779435  0.35287644  0.27455046]
 [ 1.21245498  1.33298121  0.66843429  1.75298377]
 [-1.70854928 -0.78082853 -0.22500257 -0.76110235]
 [-1.04584986 -0.50450743  0.44327917  0.53176514]
 [-1.25193564  0.44638877 -1.10450896 -1.01506725]
 [-0.33536816  0.90184529  2.72179572  0.92745718]]


array([[ 0.55467126,  0.27455046],
       [-1.04584986,  0.53176514],
       [-1.25193564, -1.01506725]])

In [118]:
# Return an error
# l = [1,3,5,3,5]
# l[:3]
# l[:3] = 5

In [119]:
l = [1,3,5,3,5]
l[:3]
l[0] = 5
l

[5, 3, 5, 3, 5]

In [120]:
l = np.array([1,3,5,3,5])
l[:3]
l[:3] = 5
l

array([5, 5, 5, 3, 5])

In [121]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(8):
    a[i] = i
print(a)    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [122]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(len(a)):
    a[i] = i
print(a) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [123]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(a.shape[0]):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [124]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i, _ in enumerate(a):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


# Transposing Arrays and Swapping Axes

In [125]:
a = np.arange(4*3).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [126]:
a.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [127]:
a.T.T.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [128]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [129]:
a.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [130]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a * b

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[ 3,  8],
       [15, 24]])

In [131]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])
# (1*3)+(2*4)
arr1.dot(arr2)

11

In [132]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a @ b

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[13, 16],
       [29, 36]])

In [133]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a.dot(b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[13, 16],
       [29, 36]])

In [134]:
print(a, a.T, sep = "\n\n", end= "\n\n")

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]



In [135]:
a.dot(a.T)

array([[ 5, 11],
       [11, 25]])

In [136]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.T

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [137]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.transpose(2,1,0)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [138]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
#a.reshape(a.shape[2], a.shape[1])
a.swapaxes(2,1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

# Table 4-3. Unary ufuncs

In [139]:
a = np.array([7,8,-20,2,-3,20])
np.abs(a) 
# return Absulote numbers eg: gradient decent optimizer /diatance

array([ 7,  8, 20,  2,  3, 20])

In [140]:
a = np.array([7,8,-20,2,-3,20])
np.fabs(a)

array([ 7.,  8., 20.,  2.,  3., 20.])

In [141]:
a = np.array([36,25,16])
np.fabs(a)

array([36., 25., 16.])

In [142]:
a = np.array([7,8,-20,2,-3,20])
np.square(a)

array([ 49,  64, 400,   4,   9, 400])

In [143]:
# Example of Eular Formula

In [144]:
np.exp(a)

array([1.09663316e+03, 2.98095799e+03, 2.06115362e-09, 7.38905610e+00,
       4.97870684e-02, 4.85165195e+08])

In [145]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.ceil(a)

array([3., 3., 3., 3.])

In [146]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.floor(a)

array([2., 2., 2., 2.])

In [147]:
a = np.array([2.8, 9.7, 5.9])
for i in a:
    i = str(i).split(".")
    print(i[0], i[1])

2 8
9 7
5 9


In [148]:
a = np.array([2.8, 9.7, 5.9])
f, w = np.modf(a)
print(w,f, sep="\n")

[2. 9. 5.]
[0.8 0.7 0.9]


In [149]:
np.isnan(np.nan)

True

In [150]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])

np.maximum(a,b)

array([3, 3, 5, 7])

In [151]:
np.fmax(a,b)

array([3, 3, 5, 7])

In [152]:
np.fmax??

Call signature:  np.fmax(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'fmax'>
File:            c:\users\hassan\appdata\local\programs\python\python310\lib\site-packages\numpy\__init__.py
Docstring:      
fmax(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Element-wise maximum of array elements.

Compare two arrays and returns a new array containing the element-wise
maxima. If one of the elements being compared is a NaN, then the
non-nan element is returned. If both elements are NaNs then the first
is returned.  The latter distinction is important for complex NaNs,
which are defined as at least one of the real or imaginary parts being
a NaN. The net effect is that NaNs are ignored when possible.

Parameters
----------
x1, x2 : array_like
    The arrays holding the elements to be compared.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the o

# 4.3 Array-Oriented Programming with Arrays

In [153]:
a = np.arange(4*3)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [154]:
np.meshgrid(a,a)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,

# Expressing Conditional Logic as Array Operations

#### np.wher(condition, value_true, value_false)

In [155]:
a = np.arange(8*4).reshape((8,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [156]:
# np.where(condition, True_block, False_block)

In [157]:
np.where(a%3 == 0, "Yes","No")

array([['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No']], dtype='<U3')

In [158]:
np.where(a%3 == 0, a,0)

array([[ 0,  0,  0,  3],
       [ 0,  0,  6,  0],
       [ 0,  9,  0,  0],
       [12,  0,  0, 15],
       [ 0,  0, 18,  0],
       [ 0, 21,  0,  0],
       [24,  0,  0, 27],
       [ 0,  0, 30,  0]])

In [159]:
[[-1,0,1],
[-1,0,1],
[-1,0,1]] #kam black xiada white

[[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]]

In [160]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])

np.where(a>b, a, b)

array([3, 3, 5, 7])

# Mathematical and Statistical Methods

In [161]:
a = np.arange(3*4).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
np.sum(a)

66

In [163]:
print(a)
np.sum(a, axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [164]:
print(a)
np.sum(a, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

##### Broad Casting

In [165]:
a = np.arange(5*5).reshape((5,5))
print(a)
a + 5

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [166]:
a = np.arange(5*5).reshape((5,5))
b = np.full_like(a, 5)
print(a,b,sep="\n\n")
a + b

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

## stacking

In [167]:
# stacking ->axis 0, 1
# vstack
# columnstack
# rowstack
# hstack
# block
# dstack

#### split

In [168]:
# split
# dsplit

# > Stackig

In [169]:
import numpy as np
a = np.random.randint(1,10, size=10)
b = a + 5
print(a, b, sep='\n')
print(len(a),len(b))

[6 2 6 3 5 6 9 1 3 1]
[11  7 11  8 10 11 14  6  8  6]
10 10


In [170]:
print(a,b, sep='\n\n')

[6 2 6 3 5 6 9 1 3 1]

[11  7 11  8 10 11 14  6  8  6]


In [171]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=0)

[6 2 6 3 5 6 9 1 3 1]

[11  7 11  8 10 11 14  6  8  6]


array([[ 6,  2,  6,  3,  5,  6,  9,  1,  3,  1],
       [11,  7, 11,  8, 10, 11, 14,  6,  8,  6]])

In [172]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=1)

[6 2 6 3 5 6 9 1 3 1]

[11  7 11  8 10 11 14  6  8  6]


array([[ 6, 11],
       [ 2,  7],
       [ 6, 11],
       [ 3,  8],
       [ 5, 10],
       [ 6, 11],
       [ 9, 14],
       [ 1,  6],
       [ 3,  8],
       [ 1,  6]])

In [173]:
# np.stack((a,b), axis=1)
np.column_stack((a,b))

array([[ 6, 11],
       [ 2,  7],
       [ 6, 11],
       [ 3,  8],
       [ 5, 10],
       [ 6, 11],
       [ 9, 14],
       [ 1,  6],
       [ 3,  8],
       [ 1,  6]])

In [174]:
np.stack((a,b), axis=0)

array([[ 6,  2,  6,  3,  5,  6,  9,  1,  3,  1],
       [11,  7, 11,  8, 10, 11, 14,  6,  8,  6]])

In [175]:
np.vstack((a,b))

array([[ 6,  2,  6,  3,  5,  6,  9,  1,  3,  1],
       [11,  7, 11,  8, 10, 11, 14,  6,  8,  6]])

In [176]:
# 
# 
np.row_stack((a,b))

array([[ 6,  2,  6,  3,  5,  6,  9,  1,  3,  1],
       [11,  7, 11,  8, 10, 11, 14,  6,  8,  6]])

In [177]:
np.hstack((a,b))

array([ 6,  2,  6,  3,  5,  6,  9,  1,  3,  1, 11,  7, 11,  8, 10, 11, 14,
        6,  8,  6])

In [178]:
np.vstack((a,b))

array([[ 6,  2,  6,  3,  5,  6,  9,  1,  3,  1],
       [11,  7, 11,  8, 10, 11, 14,  6,  8,  6]])

In [179]:
b = np.arange(3*3).reshape((3,3)) 
a = a + 5
print(a, b, sep='\n\n')

[11  7 11  8 10 11 14  6  8  6]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [180]:
import numpy as np
a = np.random.randint(1,10, size=10)
b = a + 5
print(a, b, sep='\n')
print(len(a),len(b))

[7 9 3 6 8 7 3 8 5 1]
[12 14  8 11 13 12  8 13 10  6]
10 10


In [181]:
np.vstack((a,b)) # vertically nechy aye ga student ka data

array([[ 7,  9,  3,  6,  8,  7,  3,  8,  5,  1],
       [12, 14,  8, 11, 13, 12,  8, 13, 10,  6]])

In [182]:
np.hstack((a,b)) # horizentally mila dy ga 

array([ 7,  9,  3,  6,  8,  7,  3,  8,  5,  1, 12, 14,  8, 11, 13, 12,  8,
       13, 10,  6])

In [183]:
np.column_stack((a,b))

array([[ 7, 12],
       [ 9, 14],
       [ 3,  8],
       [ 6, 11],
       [ 8, 13],
       [ 7, 12],
       [ 3,  8],
       [ 8, 13],
       [ 5, 10],
       [ 1,  6]])

In [184]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.dstack((a,b)) # DEPTH STACKING  with slide through depth

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
->SecondArray->
[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[[ 0,  1,  7,  8],
        [ 2,  3,  9, 10]],

       [[ 4,  5, 11, 12],
        [ 6,  7, 13, 14]]])

In [185]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.stack((a,b), axis=2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
->SecondArray->
[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[[[ 0,  1],
         [ 7,  8]],

        [[ 2,  3],
         [ 9, 10]]],


       [[[ 4,  5],
         [11, 12]],

        [[ 6,  7],
         [13, 14]]]])

In [186]:
np.stack??

Signature: np.stack(arrays, axis=0, out=None)
Source:   
@array_function_dispatch(_stack_dispatcher)
def stack(arrays, axis=0, out=None):
    """
    Join a sequence of arrays along a new axis.

    The ``axis`` parameter specifies the index of the new axis in the
    dimensions of the result. For example, if ``axis=0`` it will be the first
    dimension and if ``axis=-1`` it will be the last dimension.

    .. versionadded:: 1.10.0

    Parameters
    ----------
    arrays : sequence of array_like
        Each array must have the same shape.

    axis : int, optional
        The axis in the result array along which the input arrays are stacked.

    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what stack would have returned if no
        out argument were specified.

    Returns
    -------
    stacked : ndarray
        The stacked array has one more dimension than the input arrays.

    See Also


In [187]:
a.reshape((2,-1))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

# Split

In [188]:
a = np.arange(6*6).reshape((6,6))
print(a)
np.split(a, 6, axis=0)
np.split(a, 3, axis=0)
np.split(a, 2, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [189]:
a = np.arange(6*6).reshape((6,6))
print(a)
np.split(a, 6, axis=1)
np.split(a, 3, axis=1)
np.split(a, 2, axis=1)[0]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20],
       [24, 25, 26],
       [30, 31, 32]])

In [190]:
np.dsplit??

Signature: np.dsplit(ary, indices_or_sections)
Source:   
@array_function_dispatch(_hvdsplit_dispatcher)
def dsplit(ary, indices_or_sections):
    """
    Split array into multiple sub-arrays along the 3rd axis (depth).

    Please refer to the `split` documentation.  `dsplit` is equivalent
    to `split` with ``axis=2``, the array is always split along the third
    axis provided the array dimension is greater than or equal to 3.

    See Also
    --------
    split : Split an array into multiple sub-arrays of equal size.

    Examples
    --------
    >>> x = np.arange(16.0).reshape(2, 2, 4)
    >>> x
    array([[[ 0.,   1.,   2.,   3.],
            [ 4.,   5.,   6.,   7.]],
           [[ 8.,   9.,  10.,  11.],
            [12.,  13.,  14.,  15.]]])
    >>> np.dsplit(x, 2)
    [array([[[ 0.,  1.],
            [ 4.,  5.]],
           [[ 8.,  9.],
            [12., 13.]]]), array([[[ 2.,  3.],
            [ 6.,  7.]],
           [[10., 11.],
            [14., 15.]]])]
    >>> np.dsplit

In [191]:
a = np.arange(2*2*2).reshape((2,2,2))
p=print(a)

np.dsplit(a, 2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]),
 array([[[1],
         [3]],
 
        [[5],
         [7]]])]

# Table 4-6. Array set operations

In [192]:
a = np.random.randint(1,10, size=20)
print(a)
np.unique(a)

[5 8 7 5 3 9 6 9 1 1 7 1 7 7 7 5 3 7 3 1]


array([1, 3, 5, 6, 7, 8, 9])

In [193]:
piaic = np.random.randint(1,100, size=30)
cnic = np.random.randint(1,10, size=5)
print(piaic, cnic,sep='\n\n')

[63 76 61  6 36 76 56 25 28  5 27 87 50 39 37 33 41 37 55 52 74 81 33 43
 12 99 28 88 90 13]

[6 9 3 8 4]


In [194]:
[True if x in piaic else False for x in cnic]

[True, False, False, False, False]

In [195]:
[x in piaic for x in cnic]

[True, False, False, False, False]

In [196]:
["Yes" if x in piaic else "NO" for x in cnic]

['Yes', 'NO', 'NO', 'NO', 'NO']

In [197]:
print(piaic, cnic,sep='\n\n')
np.in1d(cnic, piaic)


[63 76 61  6 36 76 56 25 28  5 27 87 50 39 37 33 41 37 55 52 74 81 33 43
 12 99 28 88 90 13]

[6 9 3 8 4]


array([ True, False, False, False, False])

In [198]:
print(piaic, cnic,sep='\n\n')
c = np.in1d(cnic, piaic)
np.where(c==True,"Yes","No")

[63 76 61  6 36 76 56 25 28  5 27 87 50 39 37 33 41 37 55 52 74 81 33 43
 12 99 28 88 90 13]

[6 9 3 8 4]


array(['Yes', 'No', 'No', 'No', 'No'], dtype='<U3')

In [199]:
print(piaic, cnic,sep='\n\n')
np.intersect1d(cnic, piaic)

[63 76 61  6 36 76 56 25 28  5 27 87 50 39 37 33 41 37 55 52 74 81 33 43
 12 99 28 88 90 13]

[6 9 3 8 4]


array([6])

In [200]:
print(piaic, cnic,sep='\n\n')
np.union1d(cnic, piaic)

[63 76 61  6 36 76 56 25 28  5 27 87 50 39 37 33 41 37 55 52 74 81 33 43
 12 99 28 88 90 13]

[6 9 3 8 4]


array([ 3,  4,  5,  6,  8,  9, 12, 13, 25, 27, 28, 33, 36, 37, 39, 41, 43,
       50, 52, 55, 56, 61, 63, 74, 76, 81, 87, 88, 90, 99])

In [201]:
print(piaic, cnic,sep='\n\n')
np.setdiff1d(cnic, piaic)

[63 76 61  6 36 76 56 25 28  5 27 87 50 39 37 33 41 37 55 52 74 81 33 43
 12 99 28 88 90 13]

[6 9 3 8 4]


array([3, 4, 8, 9])

In [202]:
# XOR
# 0 0 -> 0
# 1 0 -> 1
# 0 1 -> 1
# 1 1 -> 0
print(piaic, cnic,sep='\n\n')
np.setxor1d(cnic, piaic)

[63 76 61  6 36 76 56 25 28  5 27 87 50 39 37 33 41 37 55 52 74 81 33 43
 12 99 28 88 90 13]

[6 9 3 8 4]


array([ 3,  4,  5,  8,  9, 12, 13, 25, 27, 28, 33, 36, 37, 39, 41, 43, 50,
       52, 55, 56, 61, 63, 74, 76, 81, 87, 88, 90, 99])

In [203]:
import numpy as np

a = np.arange(4).reshape(2 , 2)
print(a)

b = np.arange(4,8).reshape(2,2)
print(b)

c = np.arange(9,13).reshape(2,2)
print(c)

np.vstack((a, b,c))

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 9 10]
 [11 12]]


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 9, 10],
       [11, 12]])